project_id = "caegybyfdkmgjrygnavg"

[functions.send-notification]
verify_jwt = false

[functions.check-overtime]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.overtime-action]
verify_jwt = false

[functions.export-to-drive]
verify_jwt = false

[functions.notify-maintenance-request]
verify_jwt = false

[functions.home-assistant]
verify_jwt = false
